version: '2'

services:
  db:
    image: mariadb:10.5.9
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:5.0.11-alpine
    restart: always

  app:
    image: nextcloud:20.0.8-apache
    restart: always
    extra_hosts:
      - dockerhost:172.18.238.1
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

networks:
  default:
    ipam:
      config:
      - subnet: 172.18.238.0/24
        gateway: 172.18.238.1

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/mariadb

  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/nextcloud
